In [94]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [95]:
data= pd.read_csv("crimes_fti.csv")

# Data Description

1. Display shape of the data
2. Display top 20 rows
3. Display data types
4. Display statistical properties like MCT and Dispersion
5. Check for Null Values

In [96]:
data.shape

(65535, 17)

In [97]:
data.head(20)

INCIDENT_NUMBER  OFFENSE_CODE               OFFENSE_CODE_GROUP  \
0       I182080058          2403               Disorderly Conduct   
1       I182080053          3201                    Property Lost   
2       I182080052          2647                            Other   
3       I182080051           413               Aggravated Assault   
4       I182080050          3122                         Aircraft   
5       I182080049          1402                        Vandalism   
6       I182080048          3803  Motor Vehicle Accident Response   
7       I182080047          3301                  Verbal Disputes   
8       I182080045           802                   Simple Assault   
9       I182080044          3410                            Towed   
10      I182080043          3803  Motor Vehicle Accident Response   
11      I182080042           706                       Auto Theft   
12      I182080041          3006               Medical Assistance   
13      I182080040          3115               Investigate Person   
14      I182080039          3006               Medical Assistance   
15      I182080038          3831  Motor Vehicle Accident Response   
16      I182080037          2647                            Other   
17      I182080035          2647                            Other   
18      I182080034          3115               Investigate Person   
19      I182080031          3108             Fire Related Reports   

                      OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA SHOOTING  \
0                    DISTURBING THE PEACE      E18            495      NaN   
1                         PROPERTY - LOST      D14            795      NaN   
2               THREATS TO DO BODILY HARM       B2            329      NaN   
3          ASSAULT - AGGRAVATED - BATTERY       A1             92      NaN   
4                      AIRCRAFT INCIDENTS       A7             36      NaN   
5                               VANDALISM      C11            351      NaN   
6          M/V ACCIDENT - PERSONAL INJURY      NaN            ABC      NaN   
7                          VERBAL DISPUTE       B2            603      NaN   
8                ASSAULT SIMPLE - BATTERY      E18            543      NaN   
9                     TOWED MOTOR VEHICLE       D4            621      NaN   
10         M/V ACCIDENT - PERSONAL INJURY      D14            750      NaN   
11      AUTO THEFT - MOTORCYCLE / SCOOTER      E13            582      NaN   
12          SICK/INJURED/MEDICAL - PERSON      E18            484      NaN   
13                     INVESTIGATE PERSON       B3            427      NaN   
14          SICK/INJURED/MEDICAL - PERSON       B3            469      NaN   
15  M/V - LEAVING SCENE - PROPERTY DAMAGE      NaN            XYZ      NaN   
16              THREATS TO DO BODILY HARM      C11            385      NaN   
17              THREATS TO DO BODILY HARM       B2            326      NaN   
18                     INVESTIGATE PERSON       D4            626      NaN   
19    FIRE REPORT - HOUSE, BUILDING, ETC.      C11            338      NaN   

    OCCURRED_ON_DATE  YEAR  MONTH DAY_OF_WEEK  HOUR    UCR_PART  \
0      3/10/18 20:13  2018     10   Wednesday    20    Part Two   
1   30/08/2018 20:00  2018      8    Thursday    20  Part Three   
2      3/10/18 19:20  2018     10   Wednesday    19    Part Two   
3      3/10/18 20:00  2018     10   Wednesday    20    Part One   
4      3/10/18 20:49  2018     10   Wednesday    20  Part Three   
5      2/10/18 20:40  2018     10     Tuesday    20    Part Two   
6      3/10/18 20:16  2018     10   Wednesday    20  Part Three   
7      3/10/18 19:32  2018     10   Wednesday    19  Part Three   
8      3/10/18 19:27  2018     10   Wednesday    19    Part Two   
9      3/10/18 20:00  2018     10   Wednesday    20  Part Three   
10     3/10/18 19:33  2018     10   Wednesday    19  Part Three   
11     1/10/18 20:00  2018     10      Monday    20    Part One   
12     3/10/18 17:18  2018     10   Wednesd

In [98]:
data.dtypes

INCIDENT_NUMBER         object
OFFENSE_CODE             int64
OFFENSE_CODE_GROUP      object
OFFENSE_DESCRIPTION     object
DISTRICT                object
REPORTING_AREA          object
SHOOTING                object
OCCURRED_ON_DATE        object
YEAR                     int64
MONTH                    int64
DAY_OF_WEEK             object
HOUR                     int64
UCR_PART                object
STREET                  object
Lat                    float64
Long                   float64
Location                object
dtype: object

In [99]:
data.describe()

OFFENSE_CODE          YEAR         MONTH          HOUR           Lat  \
count  65535.000000  65535.000000  65535.000000  65535.000000  61271.000000   
mean    2352.644083   2017.992859      5.743282     13.055543     42.149419   
std     1174.988899      0.099948      2.250567      6.278597      2.728613   
min      111.000000   2015.000000      1.000000      0.000000     -1.000000   
25%     1102.000000   2018.000000      4.000000      9.000000     42.296934   
50%     3006.000000   2018.000000      6.000000     14.000000     42.325528   
75%     3202.000000   2018.000000      8.000000     18.000000     42.348209   
max     3831.000000   2018.000000     12.000000     23.000000     42.395042   

               Long  
count  61271.000000  
mean     -70.803888  
std        4.413944  
min      -71.178674  
25%      -71.097074  
50%      -71.077610  
75%      -71.062563  
max       -1.000000

In [100]:
data.describe(include="object")

INCIDENT_NUMBER               OFFENSE_CODE_GROUP  \
count            65535                            65535   
unique           58233                               60   
top         I182065208  Motor Vehicle Accident Response   
freq                10                             7572   

                  OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA SHOOTING  \
count                           65535    65022          65535      184   
unique                            179       12            880        1   
top     SICK/INJURED/MEDICAL - PERSON       B2                       Y   
freq                             4595    10022           4689      184   

        OCCURRED_ON_DATE DAY_OF_WEEK    UCR_PART         STREET  \
count              65535       65535       65518          64433   
unique             47974           7           4           3281   
top     19/07/2018 00:00      Friday  Part Three  WASHINGTON ST   
freq                  16        9975       33755           3022   

                        Location  
count                      65535  
unique                     11428  
top     (0.00000000, 0.00000000)  
freq                        4264

In [101]:
data.isnull().sum()

INCIDENT_NUMBER            0
OFFENSE_CODE               0
OFFENSE_CODE_GROUP         0
OFFENSE_DESCRIPTION        0
DISTRICT                 513
REPORTING_AREA             0
SHOOTING               65351
OCCURRED_ON_DATE           0
YEAR                       0
MONTH                      0
DAY_OF_WEEK                0
HOUR                       0
UCR_PART                  17
STREET                  1102
Lat                     4264
Long                    4264
Location                   0
dtype: int64

# Dealing with Data Quality Problems

1. Display values counts of all unique values in a column ( All columns)
2. Detect values which are incorrect
3. Handle all such incorrect values ( Only one or two columns may have incorrect values)
4. Replace all incorrect values with NaN
5. Remove all the records having Null / NaN Values
6. Remove all the columns which have more that 50 % null values

In [102]:
data["INCIDENT_NUMBER"].value_counts().unique()

array([10,  7,  6,  5,  4,  3,  2,  1], dtype=int64)

In [135]:
for col in data.columns:
    print(col)
    print(data[col].value_counts())
    print()
    
    

INCIDENT_NUMBER
I182031562    6
I182051210    6
I182037657    5
I182058835    5
I182049671    5
I182044393    5
I182031717    4
I182077113    4
I182036730    4
I182052602    3
I182045071    3
I182038763    3
I182033779    3
I182044546    3
I182033510    3
I182019313    3
I182014658    3
I182055198    3
I182053414    2
I182062810    2
I182066420    2
I182074372    2
I182070806    2
I182067317    2
I182035240    2
I182056227    2
I182074638    2
I182053289    2
I182024815    2
I182011931    2
             ..
I182022623    1
I182045765    1
I182028394    1
I182031968    1
I182064056    1
I182060309    1
I182026805    1
I182023966    1
I182011422    1
I182064699    1
I182013270    1
I182058179    1
I182070720    1
I182022093    1
I182024317    1
I182033040    1
I182070974    1
I182064057    1
I182075690    1
I182060366    1
I182064331    1
I182051203    1
I182068876    1
I182052365    1
I182044559    1
I182060953    1
I182022956    1
I182043486    1
I182076789    1
I182052372    1
Name: IN

In [136]:
for col in data.columns:
    print(col)
    print(data[col].value_counts().unique())
    print()

INCIDENT_NUMBER
[6 5 4 3 2 1]

OFFENSE_CODE
[76 20 17 14 10  6  5  4  3  2  1]

OFFENSE_CODE_GROUP
[79 22 20 17 10  5  4  2  1]

OFFENSE_DESCRIPTION
[76 20 17 14 10  6  5  4  3  2  1]

DISTRICT
[63 31 15 11  9  7  4  2  1]

REPORTING_AREA
[8 7 6 5 4 3 2 1]

SHOOTING
[175]

OCCURRED_ON_DATE
[6 5 4 3 2 1]

YEAR
[175]

MONTH
[33 28 27 22 19 11  8]

DAY_OF_WEEK
[44 35 30 25 15 11]

HOUR
[66 47 35 14 13]

UCR_PART
[101  40  34]

STREET
[9 6 5 4 3 2 1]

Lat
[6 5 4 3 2 1]

Long
[6 5 4 3 2 1]

Location
[6 5 4 3 2 1]

UCR_PART_Part One
[101  74]

UCR_PART_Part Three
[141  34]

UCR_PART_Part Two
[135  40]



In [104]:
data

INCIDENT_NUMBER  OFFENSE_CODE                OFFENSE_CODE_GROUP  \
0          I182080058          2403                Disorderly Conduct   
1          I182080053          3201                     Property Lost   
2          I182080052          2647                             Other   
3          I182080051           413                Aggravated Assault   
4          I182080050          3122                          Aircraft   
5          I182080049          1402                         Vandalism   
6          I182080048          3803   Motor Vehicle Accident Response   
7          I182080047          3301                   Verbal Disputes   
8          I182080045           802                    Simple Assault   
9          I182080044          3410                             Towed   
10         I182080043          3803   Motor Vehicle Accident Response   
11         I182080042           706                        Auto Theft   
12         I182080041          3006                Medical Assistance   
13         I182080040          3115                Investigate Person   
14         I182080039          3006                Medical Assistance   
15         I182080038          3831   Motor Vehicle Accident Response   
16         I182080037          2647                             Other   
17         I182080035          2647                             Other   
18         I182080034          3115                Investigate Person   
19         I182080031          3108              Fire Related Reports   
20         I182080030          3831   Motor Vehicle Accident Response   
21         I182080029           613                           Larceny   
22         I182080028          3114              Investigate Property   
23         I182080027          3301                   Verbal Disputes   
24         I182080027           619                           Larceny   
25         I182080026          2629                        Harassment   
26         I182080025           311                           Robbery   
27         I182080024          1842                    Drug Violation   
28         I182080023          3115                Investigate Person   
29         I182080022          3006                Medical Assistance   
...               ...           ...                               ...   
65505      I182010090          1001                    Counterfeiting   
65506      I182010089          3114              Investigate Property   
65507      I182010088          3006                Medical Assistance   
65508      I182010087           613                           Larceny   
65509      I182010086          3006                Medical Assistance   
65510      I182010083          3114              Investigate Property   
65511      I182010082          3201                     Property Lost   
65512      I182010081           802                    Simple Assault   
65513      I182010080          3115                Investigate Person   
65514      I182010078          3831   Motor Vehicle Accident Response   
65515      I182010077          3301                   Verbal Disputes   
65516      I182010076           617                           Larceny   
65517      I182010075           617                           Larceny   
65518      I182010075          1001                    Counterfeiting   
65519      I182010074          3802   Motor Vehicle Accident Response   
65520      I182010073          2647                             Other   
65521      I182010072           724                        Auto Theft   
65522      I182010071          2647                             Other   
65523      I182010071          2629                        Harassment   
65524      I182010069          3831   Motor Vehicle Accident Response   
65525      I182010068          3201                     Property Lost   
65526      I182010067          2608   Offenses Against Child / Family   
65527      I182010065          3801   Motor Vehicle Accident Res

In [105]:
data["INCIDENT_NUMBER"].duplicated().sum()

7302

In [106]:
data["INCIDENT_NUMBER"].drop_duplicates(keep="last", inplace=True)

In [107]:
data["OFFENSE_CODE_GROUP"].value_counts()

Motor Vehicle Accident Response     7572
Medical Assistance                  5527
Larceny                             5295
Investigate Person                  3747
Other                               3746
Simple Assault                      3500
Drug Violation                      3192
Verbal Disputes                     2992
Vandalism                           2801
Towed                               2642
Investigate Property                2549
Property Lost                       2418
Larceny From Motor Vehicle          2042
Aggravated Assault                  1661
Fraud                               1447
Violations                          1178
Warrant Arrests                     1042
Missing Person Located               960
Auto Theft                           927
Property Found                       913
Residential Burglary                 868
Harassment                           849
Robbery                              774
Police Service Incidents             755
Missing Person R

In [108]:
data["REPORTING_AREA"].value_counts()

        4689
111      511
186      469
624      428
329      400
465      389
26       358
143      345
117      322
175      318
427      306
134      305
130      300
304      296
520      291
627      289
428      286
900      285
337      282
282      282
355      274
311      273
914      246
444      243
330      241
328      237
288      237
177      235
170      234
94       232
        ... 
683        4
672        4
744        4
505        4
708        4
739        4
753        4
595        4
665        3
689        3
741        3
743        3
663        3
599        3
690        3
678        2
927        2
960        2
671        2
698        2
917        2
819        1
0          1
 ttt       1
218        1
XCV        1
 ABC       1
277        1
745        1
 XYZ       1
Name: REPORTING_AREA, Length: 880, dtype: int64

In [109]:
cnt=0
for row in data['REPORTING_AREA']:
    if(len(str(row))!=3)or (any(c.isalpha()for c in row)):
        data.loc[cnt,'REPORTING_AREA']=np.nan
    cnt+=1

In [110]:
data["REPORTING_AREA"].head()

0    495
1    795
2    329
3    NaN
4    NaN
Name: REPORTING_AREA, dtype: object

In [111]:
data["YEAR"].value_counts()

2018    65146
2017      326
2016       47
2015       16
Name: YEAR, dtype: int64

In [112]:
data['MONTH'].value_counts()

5     8947
6     8893
8     8659
7     8626
9     8176
4     7923
3     7739
2     5492
10     741
1      206
12      83
11      50
Name: MONTH, dtype: int64

In [113]:
data["DAY_OF_WEEK"].value_counts()

Friday       9975
Wednesday    9712
Thursday     9712
Tuesday      9419
Monday       9327
Saturday     9197
Sunday       8193
Name: DAY_OF_WEEK, dtype: int64

In [114]:
data["UCR_PART"].value_counts()

Part Three    33755
Part Two      19615
Part One      11884
Other           264
Name: UCR_PART, dtype: int64

In [115]:
data.dropna(axis=0,inplace=True)
data.reset_index(drop=True, inplace=True )

In [116]:
data.shape

(175, 17)

In [117]:
data.dropna(axis=1, thresh=0.50*len(data),inplace=True)
data.reset_index(drop=True, inplace=True )

In [118]:
data.shape

(175, 17)

In [119]:
data.isnull().sum()

INCIDENT_NUMBER        0
OFFENSE_CODE           0
OFFENSE_CODE_GROUP     0
OFFENSE_DESCRIPTION    0
DISTRICT               0
REPORTING_AREA         0
SHOOTING               0
OCCURRED_ON_DATE       0
YEAR                   0
MONTH                  0
DAY_OF_WEEK            0
HOUR                   0
UCR_PART               0
STREET                 0
Lat                    0
Long                   0
Location               0
dtype: int64

# Feature Encoding and Discretization

1. Apply label encoding to OFFENSE_CODE_GROUP and DAY_OF_WEEK
2. Apply One-Hot Encoding to UCR_PART
3. Apply Discretization to HOUR (0-8 Early Morning , 8-12 Morning 12-16 Afternoon, 16-19 Evening, 19-23 Night) or you can create your own levels.

In [120]:
from numpy import array
from sklearn.preprocessing import LabelEncoder

In [121]:
data.head(3)

INCIDENT_NUMBER  OFFENSE_CODE  OFFENSE_CODE_GROUP  \
0      I182078893           413  Aggravated Assault   
1      I182078893          2662          Ballistics   
2      I182078872           413  Aggravated Assault   

              OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA SHOOTING  \
0  ASSAULT - AGGRAVATED - BATTERY      C11            416        Y   
1       BALLISTICS EVIDENCE/FOUND      C11            416        Y   
2  ASSAULT - AGGRAVATED - BATTERY       B2            330        Y   

   OCCURRED_ON_DATE  YEAR  MONTH DAY_OF_WEEK  HOUR  UCR_PART         STREET  \
0  29/09/2018 21:12  2018      9    Saturday    21  Part One  WASHINGTON ST   
1  29/09/2018 21:12  2018      9    Saturday    21  Part Two  WASHINGTON ST   
2  29/09/2018 19:21  2018      9    Saturday    19  Part One      SEAVER ST   

         Lat       Long                     Location  
0  42.281647 -71.071118  (42.28164735, -71.07111848)  
1  42.281647 -71.071118  (42.28164735, -71.07111848)  
2  42.304554 -71.082954  (42.30455372, -71.08295366)

In [122]:
label_encoder = LabelEncoder()
data["OFFENSE_CODE_GROUP"] = label_encoder.fit_transform(data["OFFENSE_CODE_GROUP"])
data.head(3)

INCIDENT_NUMBER  OFFENSE_CODE  OFFENSE_CODE_GROUP  \
0      I182078893           413                   0   
1      I182078893          2662                   1   
2      I182078872           413                   0   

              OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA SHOOTING  \
0  ASSAULT - AGGRAVATED - BATTERY      C11            416        Y   
1       BALLISTICS EVIDENCE/FOUND      C11            416        Y   
2  ASSAULT - AGGRAVATED - BATTERY       B2            330        Y   

   OCCURRED_ON_DATE  YEAR  MONTH DAY_OF_WEEK  HOUR  UCR_PART         STREET  \
0  29/09/2018 21:12  2018      9    Saturday    21  Part One  WASHINGTON ST   
1  29/09/2018 21:12  2018      9    Saturday    21  Part Two  WASHINGTON ST   
2  29/09/2018 19:21  2018      9    Saturday    19  Part One      SEAVER ST   

         Lat       Long                     Location  
0  42.281647 -71.071118  (42.28164735, -71.07111848)  
1  42.281647 -71.071118  (42.28164735, -71.07111848)  
2  42.304554 -71.082954  (42.30455372, -71.08295366)

In [123]:
data['DAY_OF_WEEK'] = label_encoder.fit_transform(data['DAY_OF_WEEK'])
data.head(3)

INCIDENT_NUMBER  OFFENSE_CODE  OFFENSE_CODE_GROUP  \
0      I182078893           413                   0   
1      I182078893          2662                   1   
2      I182078872           413                   0   

              OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA SHOOTING  \
0  ASSAULT - AGGRAVATED - BATTERY      C11            416        Y   
1       BALLISTICS EVIDENCE/FOUND      C11            416        Y   
2  ASSAULT - AGGRAVATED - BATTERY       B2            330        Y   

   OCCURRED_ON_DATE  YEAR  MONTH  DAY_OF_WEEK  HOUR  UCR_PART         STREET  \
0  29/09/2018 21:12  2018      9            2    21  Part One  WASHINGTON ST   
1  29/09/2018 21:12  2018      9            2    21  Part Two  WASHINGTON ST   
2  29/09/2018 19:21  2018      9            2    19  Part One      SEAVER ST   

         Lat       Long                     Location  
0  42.281647 -71.071118  (42.28164735, -71.07111848)  
1  42.281647 -71.071118  (42.28164735, -71.07111848)  
2  42.304554 -71.082954  (42.30455372, -71.08295366)

In [124]:
data.columns

Index(['INCIDENT_NUMBER', 'OFFENSE_CODE', 'OFFENSE_CODE_GROUP',
       'OFFENSE_DESCRIPTION', 'DISTRICT', 'REPORTING_AREA', 'SHOOTING',
       'OCCURRED_ON_DATE', 'YEAR', 'MONTH', 'DAY_OF_WEEK', 'HOUR', 'UCR_PART',
       'STREET', 'Lat', 'Long', 'Location'],
      dtype='object')

In [125]:
data['UCR_PART'].dtypes

dtype('O')

In [126]:
data['UCR_PART'] = pd.Categorical(data['UCR_PART'])

In [128]:
dummy = pd.get_dummies(data['UCR_PART'], prefix = 'UCR_PART')

In [129]:
dummy.head()

UCR_PART_Part One  UCR_PART_Part Three  UCR_PART_Part Two
0                  1                    0                  0
1                  0                    0                  1
2                  1                    0                  0
3                  1                    0                  0
4                  0                    0                  1

In [130]:
data = pd.concat([data, dummy], axis=1)

In [131]:
data.head()

INCIDENT_NUMBER  OFFENSE_CODE  OFFENSE_CODE_GROUP  \
0      I182078893           413                   0   
1      I182078893          2662                   1   
2      I182078872           413                   0   
3      I182077958           413                   0   
4      I182077958          2662                   1   

              OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA SHOOTING  \
0  ASSAULT - AGGRAVATED - BATTERY      C11            416        Y   
1       BALLISTICS EVIDENCE/FOUND      C11            416        Y   
2  ASSAULT - AGGRAVATED - BATTERY       B2            330        Y   
3  ASSAULT - AGGRAVATED - BATTERY       B3            428        Y   
4       BALLISTICS EVIDENCE/FOUND       B3            428        Y   

   OCCURRED_ON_DATE  YEAR  MONTH  DAY_OF_WEEK  HOUR  UCR_PART         STREET  \
0  29/09/2018 21:12  2018      9            2    21  Part One  WASHINGTON ST   
1  29/09/2018 21:12  2018      9            2    21  Part Two  WASHINGTON ST   
2  29/09/2018 19:21  2018      9            2    19  Part One      SEAVER ST   
3  26/09/2018 20:20  2018      9            6    20  Part One      MORTON ST   
4  26/09/2018 20:20  2018      9            6    20  Part Two      MORTON ST   

         Lat       Long                     Location  UCR_PART_Part One  \
0  42.281647 -71.071118  (42.28164735, -71.07111848)                  1   
1  42.281647 -71.071118  (42.28164735, -71.07111848)                  0   
2  42.304554 -71.082954  (42.30455372, -71.08295366)                  1   
3  42.283746 -71.089382  (42.28374593, -71.08938232)                  1   
4  42.283746 -71.089382  (42.28374593, -71.08938232)                  0   

   UCR_PART_Part Three  UCR_PART_Part Two  
0                    0                  0  
1                    0                  1  
2                    0                  0  
3                    0                  0  
4                    0                  1

Apply Discretization to HOUR (0-8 Early Morning , 8-12 Morning 12-16 Afternoon, 16-19 Evening, 19-23 Night) or you can create your own levels.

In [132]:
data['HOUR']  = np.where((data['HOUR'] <8) ,'Early Morning',
                               np.where((data['HOUR'] >=8) & (data['HOUR'] <=12),'Morning',
                               np.where((data['HOUR']>12) & (data['HOUR'] <=16),'Afternoon',
                               np.where((data['HOUR']>16) & (data['HOUR'] <=19),'Evening',
                                       'Night'))))

In [133]:
data.head(19)

INCIDENT_NUMBER  OFFENSE_CODE  OFFENSE_CODE_GROUP  \
0       I182078893           413                   0   
1       I182078893          2662                   1   
2       I182078872           413                   0   
3       I182077958           413                   0   
4       I182077958          2662                   1   
5       I182077113           413                   0   
6       I182077113          1510                   3   
7       I182077113          3130                  10   
8       I182077113          1501                   3   
9       I182076987           413                   0   
10      I182076789           111                   4   
11      I182076074           413                   0   
12      I182075690           413                   0   
13      I182074638          3114                   6   
14      I182074638           413                   0   
15      I182074555           111                   4   
16      I182074555          3115                   5   
17      I182074372           413                   0   
18      I182074372          2662                   1   

                              OFFENSE_DESCRIPTION DISTRICT REPORTING_AREA  \
0                  ASSAULT - AGGRAVATED - BATTERY      C11            416   
1                       BALLISTICS EVIDENCE/FOUND      C11            416   
2                  ASSAULT - AGGRAVATED - BATTERY       B2            330   
3                  ASSAULT - AGGRAVATED - BATTERY       B3            428   
4                       BALLISTICS EVIDENCE/FOUND       B3            428   
5                  ASSAULT - AGGRAVATED - BATTERY       B2            276   
6              WEAPON - FIREARM - OTHER VIOLATION       B2            276   
7                                  SEARCH WARRANT       B2            276   
8   WEAPON - FIREARM - CARRYING / POSSESSING, ETC       B2            276   
9                  ASSAULT - AGGRAVATED - BATTERY       D4            156   
10            MURDER, NON-NEGLIGIENT MANSLAUGHTER      E13            651   
11                 ASSAULT - AGGRAVATED - BATTERY      C11            334   
12                 ASSAULT - AGGRAVATED - BATTERY       B2            261   
13                           INVESTIGATE PROPERTY       D4            157   
14                 ASSAULT - AGGRAVATED - BATTERY       D4            157   
15            MURDER, NON-NEGLIGIENT MANSLAUGHTER       B2            330   
16                             INVESTIGATE PERSON       B2            330   
17                 ASSAULT - AGGRAVATED - BATTERY      C11            257   
18                      BALLISTICS EVIDENCE/FOUND      C11            257   

   SHOOTING  OCCURRED_ON_DATE  YEAR  MONTH  DAY_OF_WEEK           HOUR  \
0         Y  29/09/2018 21:12  2018      9            2          Night   
1         Y  29/09/2018 21:12  2018      9            2          Night   
2         Y  29/09/2018 19:21  2018      9            2        Evening   
3         Y  26/09/2018 20:20  2018      9            6          Night   
4         Y  26/09/2018 20:20  2018      9            6          Night   
5         Y  24/09/2018 06:20  2018      9            1  Early Morning   
6         Y  24/09/2018 06:20  2018      9            1  Early Morning   
7         Y  24/09/2018 06:20  2018      9            1  Early Morning   
8         Y  24/09/2018 06:20  2018      9            1  Early Morning   
9         Y  23/09/2018 13:53  2018      9            3      Afternoon   
10        Y  22/09/2018 21:46  2018      9            2          Night   
11        Y  20/09/2018 17:10  2018      9            4        Evening   
12        Y  19/09/2018 14:18  2018      9            6      Afternoon   
13        Y  16/09/2018 03:17  2018      9            3  Early Morning   
14        Y  16/09/2018 03:17  2018      9            3  Early Morning   
15        Y  15/09/2018 20:10  2018      9            2          Night   
16        Y  15/09/2018 20:10  2018      9            2          Night   
17       