## This is solved by using Numpy
1. Upload the dataset in Jupyter Notebook,
2. Load the dataset using the following code.

In [46]:
import pandas as pd
import numpy as np

In [47]:
scores = pd.read_excel("Score.xlsx", skipinitialspace=True)

3. Print the scores.

In [48]:
print(scores)

                        Name  English  Mathematics
0           Muhammad Abubakr       93           90
1                Yamna Tahir       90           45
2                Waqar - FTI       40           80
3        Khoulah Afzal Qamar       93           76
4             Ali Ibad Brohi       43           56
5             Maad Saifuddin       80           59
6               Hassan Ahmed       71           30
7          Hamza Quaid Joher       90           89
8            M. Umair Munshi       73           90
9                 Rama Abrik       93           87
10              Qaisar Nisar       78           45
11  Muhammad Sami Ullah Khan       40           60
12     Hafiz Muhammad Shahid       47           90
13      Syed Ahmed Ali Naqvi       23           40
14              Daniyal Khan       45           70
15       Hussain Murtaza Ali       76           39
16              Uzair Irshad       86           88
17              Noman-Ul-Haq       42           78
18      Muhammad Usama Ovais   

4. Set the name column as the index.

In [49]:
scores.set_index("Name", inplace=True)

5. Convert the loaded data into a numpy array.

In [50]:
np_scores = np.array(scores)

6. Report the maximum score in Mathematics.

In [51]:
np_Math_array = np.array(scores.Mathematics)

In [52]:
np_Math_array

array([90, 45, 80, 76, 56, 59, 30, 89, 90, 87, 45, 60, 90, 40, 70, 39, 88,
       78, 60, 87], dtype=int64)

In [53]:
np.max(np_Math_array)

90

7. Report the minimum score Mathematics.

In [54]:
np.min(np_Math_array)

30

8. Report the maximum score in English.

In [55]:
np_Eng_array = np.array(scores.English)

In [56]:
np.max(np_Eng_array)

93

9. Report the minimum score in English.

In [57]:
np.min(np_Eng_array)

23

10. Sort the list by English scores.

In [58]:
np.sort(np_Eng_array)

array([23, 38, 40, 40, 42, 43, 45, 47, 71, 73, 76, 78, 80, 86, 90, 90, 90,
       93, 93, 93], dtype=int64)

11. Sort the list by Mathematics scores.

In [59]:
np.sort(np_Math_array)

array([30, 39, 40, 45, 45, 56, 59, 60, 60, 70, 76, 78, 80, 87, 87, 88, 89,
       90, 90, 90], dtype=int64)

12. Find the mean score of each subject.

In [60]:
print("The Mean of Mathematics:",np.mean(np_Math_array))
print("The Mean of English:",np.mean(np_Eng_array))


The Mean of Mathematics: 67.95
The Mean of English: 66.55


13. Filter the English scores that are greater than 90.

In [61]:
# we can also make the conditions in variable and put it into the breakets... 
np_Eng_array[np_Eng_array > 90]

array([93, 93, 93], dtype=int64)

14. Filter the Mathematics scores that are below 50.

In [62]:
np_Math_array[np_Math_array<50]

array([45, 30, 45, 40, 39], dtype=int64)

15. Find the correlation between the two subjects.

In [63]:
np.corrcoef(np_Math_array, np_Eng_array)

array([[1.        , 0.25186155],
       [0.25186155, 1.        ]])

16. Add another column to the numpy array with the heading Science and using
the random function generate 20 numbers between 0 and 100 and add them
to the Science column.

In [64]:
science = np.random.randint(0,100,20)

In [65]:
np_scores = np.insert(np_scores,2,science, axis = 1)

In [66]:
np_scores

array([[93, 90, 49],
       [90, 45, 41],
       [40, 80, 82],
       [93, 76, 57],
       [43, 56, 32],
       [80, 59, 14],
       [71, 30, 19],
       [90, 89, 54],
       [73, 90, 92],
       [93, 87, 78],
       [78, 45, 52],
       [40, 60,  0],
       [47, 90, 84],
       [23, 40, 25],
       [45, 70, 78],
       [76, 39, 97],
       [86, 88, 72],
       [42, 78,  5],
       [38, 60,  7],
       [90, 87,  7]], dtype=int64)